services:
  - type: web
    name: ats-resume-optimizer
    env: python
    plan: free
    buildCommand: |
      npm install
      npm run build
      pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY_HERE
      - key: OPENAI_MODEL
        value: gpt-4o-mini
    healthCheckPath: /
